### ISSUE TITLE
does having a 'latest' folder matter

### ISSUE THREAD

**Issue by KAllan357** [RiotGamesCookbooks/artifact-cookbook#24]
If the version you want is provided as `latest` and the `artifact_location` is not a Nexus, you will still end up with a `latest` folder.

The condition in the Library should probably change to:

`if version.casecmp("latest") == 0 && is_nexus?(artifact_location)`

but the question is, should it?

**Comment by ivey** [comment]
Is this addressed in #31?

**Comment by KAllan357** [comment]
Yes, #31 will fix both the bug itself and partly solve this. I think the question is still valid.

We've sorta set a precedent in other cookbooks where:

``` Ruby
the_version = node.default[:version]
the_location = node.default[:location]
if local_deploy?
  the_version = "latest"
  the_location = "my/mounted/artifact"
end

artifact_deploy "my-artifact" do
  version the_version
  location the_location
  ...
end
```

So local deploys still get a `latest` folder. Is that bad?

**Comment by ivey** [comment]
Got it. Yes, that's annoying but I don't see any way to fix it, short of looking in `my/mounted/artifact` and parsing the filenames. Regardless, I don't personally think it's something the artifact cookbook should fix.

**Comment by KAllan357** [comment]
This shouldn't matter. Closing.
